android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
android.nonTransitiveRResources=true
android.nonFinalResIds=false
org.gradle.jvmargs=-Xmx5g -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.parallel=true
