const c=document.querySelector('#game'),g=c.getContext('2d'),hint=document.querySelector('#hint');let W=0,H=0,mode='menu',hero=0,frame=0,last=0,cam={x:10,y:10},p={x:10,y:10,dir:0},keys={},hud,controlMode=localStorage.getItem('controls')||'dpad';
const img=n=>{let i=new Image();i.src='assets/'+n;return i};const A={title:img('title.png')};
const heroes=[['Воин','Бывший страж деревни, ищущий пропавшую сестру.','sheet_hero_warrior.png'],['Ассассин','Изгнанница гильдии, вернувшаяся за древним клинком.','sheet_hero_assassin.png'],['Рыцарь','Защитник северных ворот.','sheet_hero_knight.png'],['Стрелок','Охотник, знающий каждый лесной след.','sheet_hero_ranger.png'],['Ганблейдер','Наёмник с экспериментальным оружием.','sheet_hero_gunblade.png'],['Элементалист','Ученик стихий, скрывающий большую силу.','sheet_hero_mage.png']];heroes.forEach(x=>x.push(img(x[2])));
const enemies=['sheet_enemy_slime.png','sheet_enemy_bat.png','sheet_enemy_goblin.png','sheet_enemy_skeleton.png'].map(img);const npc={elder:img('sheet_npc_villager.png'),merchant:img('sheet_npc_merchant.png'),smith:img('sheet_npc_blacksmith.png')};const buildings={inn:img('sheet_building_inn.png'),smith:img('sheet_building_blacksmith.png'),shrine:img('sheet_building_shrine.png')};
const objects=[{x:4,y:4,type:'elder',name:'Старейшина Эльда',text:'Тьма проснулась в руинах храма. Найди три осколка печати и возвращайся ко мне.'},{x:15,y:4,type:'merchant',name:'Торговец Рен',text:'Зелья и карты для тех, кто осмелится идти в руины.'},{x:4,y:15,type:'smith',name:'Кузнец Бран',text:'Принеси мне железную руду — я усилю оружие героя.'},{x:15,y:15,type:'shrine',name:'Святилище света',text:'Здесь можно восстановить здоровье и открыть следующую часть истории.'}];
function resize(){W=innerWidth;H=innerHeight;c.width=W*devicePixelRatio;c.height=H*devicePixelRatio;g.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function panel(html){document.querySelectorAll('.panel').forEach(x=>x.remove());let d=document.createElement('div');d.className='panel';d.innerHTML=html;document.body.append(d);return d}
function menu(){mode='menu';let d=panel(`<img src="assets/title.png" style="width:min(400px,80%);image-rendering:auto"><h1>HEROES LORE ZERO</h1><p>Глава I: Пепел забытого храма</p><button class="good" id="go">НАЧАТЬ ИГРУ</button><button id="ctrl">УПРАВЛЕНИЕ</button>`);d.querySelector('#go').onclick=select;d.querySelector('#ctrl').onclick=()=>{let q=panel(`<h1>УПРАВЛЕНИЕ</h1><p>Выбери схему управления:</p><button id="d">D-PAD + A/B</button><button id="g">ВИРТУАЛЬНЫЙ ГЕЙМПАД</button><p id="chosen">Сейчас: ${controlMode==='dpad'?'D-PAD':'ГЕЙМПАД'}</p><button onclick="this.parentNode.remove()">НАЗАД</button>`);q.querySelector('#d').onclick=()=>{controlMode='dpad';localStorage.controls='dpad';q.querySelector('#chosen').textContent='Сейчас: D-PAD'};q.querySelector('#g').onclick=()=>{controlMode='gamepad';localStorage.controls='gamepad';q.querySelector('#chosen').textContent='Сейчас: ГЕЙМПАД'}}}
function select(){mode='select';let d=panel('<h1>ВЫБОР ГЕРОЯ</h1><p>У каждого героя своя история в первой деревне.</p><div class="cards" id="cards"></div><button class="good" id="start">НАЧАТЬ ПРИКЛЮЧЕНИЕ</button>');let box=d.querySelector('#cards');heroes.forEach((h,i)=>{let q=document.createElement('article');q.className='card';q.innerHTML=`<h2>${h[0]}</h2><img style="width:64px;height:64px;image-rendering:pixelated" src="assets/${h[2]}"><p>${h[1]}</p>`;q.onclick=()=>{hero=i;select()};box.append(q)});d.querySelector('#start').onclick=()=>{d.remove();start()}}
function start(){mode='world';makeHud();hint.textContent='A: действие • B: способность • M: инвентарь • движение только D-pad'}
function makeHud(){hud=document.createElement('div');hud.className='hud';hud.innerHTML=controlMode==='dpad'?'<div class="dpad"><button class="u">▲</button><button class="d">▼</button><button class="l">◀</button><button class="r">▶</button><button class="c"></button></div><div class="actions"><button class="a">A</button><button class="b">B</button></div>':'<div class="gamepad"><div class="gp-left"><button class="gp-l1">L1</button><button class="gp-l2">L2</button><button class="gu">▲</button><button class="gd">▼</button><button class="gl">◀</button><button class="gr">▶</button><button class="gp-l3">L3</button><button class="gp-stick left-stick"></button></div><div class="gp-top"><button>🎮</button><button class="gp-menu">☰</button></div><div class="gp-right"><button class="gp-r1">R1</button><button class="gp-r2">R2</button><button class="gx">X</button><button class="gy">Y</button><button class="gb">B</button><button class="ga">A</button><button class="gp-r3">R3</button><button class="gp-stick right-stick"></button></div></div>';document.body.append(hud);let dir={};hud.querySelectorAll('.dpad button,.gamepad button').forEach(b=>{b.onpointerdown=e=>{e.stopPropagation();dir[b.className]=1};b.onpointerup=b.onpointercancel=()=>dir[b.className]=0});const action=hud.querySelector('.a,.ga');if(action)action.onpointerdown=()=>interact();const skill=hud.querySelector('.b,.gb');if(skill)skill.onpointerdown=()=>hint.textContent='Способность героя активирована';}
function interact(){let o=objects.find(o=>Math.hypot(o.x-p.x,o.y-p.y)<1.8);if(o)panel(`<h1>${o.name}</h1><p>${o.text}</p><button class="good" onclick="this.parentNode.remove()">ПРОДОЛЖИТЬ</button>`);else hint.textContent='Рядом нет персонажа или объекта'}
function update(dt){let dx=0,dy=0;if(keys.ArrowLeft)dx--;if(keys.ArrowRight)dx++;if(keys.ArrowUp)dy--;if(keys.ArrowDown)dy++;if(hud){let q=x=>{let e=hud.querySelector(x);return e&&e.matches(':active')};if(controlMode==='dpad'){if(q('.l'))dx--;if(q('.r'))dx++;if(q('.u'))dy--;if(q('.d'))dy++}else{if(q('.gl'))dx--;if(q('.gr'))dx++;if(q('.gu'))dy--;if(q('.gd'))dy++}}if(dx||dy){p.dir=Math.abs(dx)>Math.abs(dy)?dx>0?2:3:dy>0?0:1;let l=Math.hypot(dx,dy);p.x=Math.max(1,Math.min(19,p.x+dx/l*dt*3));p.y=Math.max(1,Math.min(19,p.y+dy/l*dt*3))}cam.x+=(p.x-cam.x)*.15;cam.y+=(p.y-cam.y)*.15}
function sprite(im,x,y,s,row=0,col=Math.floor(frame/8)%4){if(!im.complete)return;g.drawImage(im,col*64,row*64,64,64,x-s/2,y-s*.8,s,s)}
function draw(){g.fillStyle='#071024';g.fillRect(0,0,W,H);let s=Math.min(W,H)/18,ox=W/2-cam.x*s,oy=H/2-cam.y*s;for(let y=0;y<20;y++)for(let x=0;x<20;x++){let z=(x<10?0:1)+(y<10?0:2);g.fillStyle=['#456d35','#365f43','#5a573d','#3e6870'][z];g.fillRect(ox+x*s,oy+y*s,s+1,s+1)}g.fillStyle='#c39a59';g.fillRect(ox+9*s,oy+s,2*s,18*s);g.fillRect(ox+s,oy+9*s,18*s,2*s);objects.forEach(o=>{let xx=ox+o.x*s,yy=oy+o.y*s;if(o.type==='shrine')g.fillStyle='#b3c6ff';else g.fillStyle='#8d5542';g.fillRect(xx-s,yy-s,2*s,1.3*s);sprite(npc[o.type],xx,yy,s*.8,0)});sprite(heroes[hero][3],ox+p.x*s,oy+p.y*s,s*1.15,p.dir);for(let i=0;i<8;i++){let x=3+(i*7)%15,y=6+(i*11)%12;if(Math.hypot(x-p.x,y-p.y)>2)sprite(enemies[i%enemies.length],ox+x*s,oy+y*s,s*.8,0)}g.fillStyle='#fff';g.font='bold 14px system-ui';g.fillText(`${heroes[hero][0]}  •  Глава I`,16,26);g.fillText('Старая площадь  |  Лес  |  Руины  |  Водяные сады',16,48)}
function loop(t){let dt=Math.min(.05,(t-last)/1000||0);last=t;frame++;if(mode==='world'){update(dt);draw()}requestAnimationFrame(loop)}addEventListener('keydown',e=>{keys[e.key]=1;if(e.key.toLowerCase()==='m'&&mode==='world')panel('<h1>ИНВЕНТАРЬ</h1><p>Оружие • Броня • Зелья • Ключи • Амулеты</p><button onclick="this.parentNode.remove()">ЗАКРЫТЬ</button>');if(e.key===' '&&mode==='world')interact()});addEventListener('keyup',e=>keys[e.key]=0);menu();requestAnimationFrame(loop);
