plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'com.heroeslore.v1'
    compileSdk 34
    defaultConfig {
        applicationId 'com.heroeslore.v1'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
        resourceConfigurations += ["ru"]
    }
    signingConfigs {
        debug {
        }
        release {
            storeFile file(System.getenv('KEYSTORE_PATH') ?: 'keystore.jks')
            storePassword System.getenv('KEYSTORE_PASS') ?: 'heroes123'
            keyAlias System.getenv('KEYSTORE_ALIAS') ?: 'hl'
            keyPassword System.getenv('KEYSTORE_PASS') ?: 'heroes123'
            enableV1Signing true
            enableV2Signing true
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            crunchPngs true
        }
        debug {
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            debuggable true
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            crunchPngs true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    packaging {
        resources.excludes += ["META-INF/**"]
    }
    androidResources {
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }
}
dependencies {
    implementation "androidx.core:core-ktx:1.12.0"
}
